return {
  code = {
    Array = "",
    Boolean = "",
    Class = "󰠱",
    -- Class = "",
    Color = "󰏘",
    Constant = "󰏿",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "󰇽",
    File = "󰈙",
    Folder = "󰉋",
    Function = "󰊕",
    Interface = "",
    Key = "",
    Keyword = "󰌋",
    Method = "",
    Module = "",
    Namespace = "",
    Operator = "󰆕",
    Null = "󰟢",
    Number = "",
    Object = "",
    Package = "",
    Property = "󰜢",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    -- Struct = ""
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "󰎠",
    Variable = "",
  },

  git = {
    Git = "󰊢",
    GitAdd = "",
    GitBranch = "",
    GitChange = "",
    GitConflict = "",
    GitDelete = "",
    GitIgnored = "◌",
    GitRenamed = "➜",
    GitSign = "▎",
    GitStaged = "✓",
    GitUnstaged = "✗",
    GitUntracked = "",
  },

  dap = {
    DapBreakpoint = "",
    DapBreakpointCondition = "",
    DapBreakpointRejected = "",
    DapLogPoint = ".>",
    DapStopped = "󰁕",
    Debugger = "",
  },

  file = {
    DefaultFile = "󰈙",
    FileNew = "",
    FileModified = "",
    FileReadOnly = "",
  },

  folder = {
    FoldClosed = "",
    FoldOpened = "",
    FoldSeparator = " ",
    FolderClosed = "",
    FolderEmpty = "",
    FolderOpen = "",
  },

  diagnostic = {
    Diagnostic = "󰒡",
    Error = "󰈸",
    Warn = "",
    Hint = "󰌪",
    Info = "",
  },

  other = {
    ActiveLSP = "",
    ActiveTS = "",
    ArrowLeft = "",
    ArrowRight = "",
    Bookmarks = "",
    BufferClose = "󰅖",
    Code = "",
    Ellipsis = "…",
    Forward = "",
    History = "",
    MacroRecording = "",
    Package = "󰏖",
    Paste = "󰅌",
    Refresh = "",
    Scopes = "",
    Search = "",
    Selected = "❯",
    Session = "󱂬",
    Sort = "󰒺",
    Spellcheck = "󰓆",
    Tab = "󰓩",
    TabClose = "󰅙",
    Terminal = "",
    Window = "",
    WordFile = "󰈭",

    DiagnosticError = "",
    DiagnosticHint = "󰌵",
    DiagnosticInfo = "󰋼",
    DiagnosticWarn = "",
  },
}
