vim.g.mapleader = " "
local opt = vim.opt

opt.colorcolumn    = "80"                              -- 第80列高亮
opt.clipboard      = "unnamedplus"                     -- 使用剪切板
opt.completeopt    = "menu"                            -- 开启补全菜单
opt.completeopt    = opt.completeopt + "menuone"       -- 只有一个选项也显示菜单
opt.completeopt    = opt.completeopt + "noselect"      -- 不自动选择补全项
opt.cursorline     = true                              -- 当前行高亮
opt.expandtab      = true                              -- 使用空格组成tab
opt.foldlevelstart = 99                                -- 开始时关闭所有折叠
opt.foldmethod     = "indent"                          -- 折叠方法
opt.hlsearch       = false                             -- 关闭搜索匹配高亮
opt.ignorecase     = true                              -- 搜索时忽略大小写
opt.list           = true                              -- 通过字符展示不可见的符号
opt.listchars      = {
  nbsp             = '⦸',                              -- 不可中断的空格
  extends          = '»',                              -- 右侧超出屏幕
  precedes         = '«',                              -- 左侧超出屏幕
  tab              = '▷⋯',                             -- 制表符
  trail            = '•',                              -- 尾部空格
}
opt.number         = true                              -- 显示行数
opt.pumheight      = 12                                -- popup menu的最大高度
opt.relativenumber = true                              -- 显示相对行数
opt.scrolloff      = 3                                 -- 向上/下跳行浏览时，与顶部/底部隔3行
opt.sidescrolloff  = 3                                 -- 左右隔3行
opt.shiftwidth     = 2                                 -- 缩进的空格数
opt.showmode       = false                             -- 不显示模式
opt.smartcase      = true                              -- 搜索时智能匹配
opt.softtabstop    = 2                                 -- 两个空格代替tab
opt.splitbelow     = true                              -- 向下分屏
opt.splitright     = true                              -- 向右分屏
opt.swapfile       = false                             -- 不创建swap文件
opt.tabstop        = 2                                 -- 一个tab使用两个空格
opt.termguicolors  = true                              -- 终端中使用guifg/guibg代替ctermfg/ctermbg
opt.undofile       = true                              -- 使用undo文件
opt.visualbell     = true                              -- 关闭声音
opt.wrap           = false                             -- 不换行
opt.writebackup    = false                             -- 编辑时不备份
