require('plugin.nvim-tree')
require('plugin.treesitter')
require('plugin.nvim-cmp')
require('plugin.toggleterm')
require('plugin.autopairs')
require('plugin.comment')
require('plugin.lualine')
require('plugin.telescope')
-- require('plugin.github-theme')
